//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrators
    {
        public int Id { get; set; }
        public string Lastname { get; set; }
        public string Fitstname { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Date { get; set; }
        public string Address { get; set; }
        public string TelephonNum { get; set; }
        public string Passport { get; set; }
        public int AdministratorRole_FK { get; set; }
        public int Oklad { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual AdministratoRole AdministratoRole { get; set; }
    }
}
