//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seanses
    {
        public System.DateTime Date { get; set; }
        public int TicketCount { get; set; }
        public int Films_FK_ID { get; set; }
        public int Id { get; set; }
    
        public virtual Films Films { get; set; }
    }
}
