//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seats
    {
        public int SeatId { get; set; }
        public int Row { get; set; }
        public int Colunt { get; set; }
        public int Seanses_Id_FK { get; set; }
        public int Users_Id_FK { get; set; }
        public int Tickets_Id_FK { get; set; }
    
        public virtual Seanses Seanses { get; set; }
        public virtual Tickets Tickets { get; set; }
        public virtual Users Users { get; set; }
    }
}
